# This workflow updates java documentation automatically
name: docs

on:
  push:
    branches: [ main ]
    paths: [ '**.java' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build docs with Maven
      run: mvn javadoc:javadoc

    - name: Copy to Documentation Website Location
      run: |
        rm -rf docs
        cp -rf target/site/apidocs/. docs

    - name: Tidy up the javadocs
      id: tidy
      uses: cicirello/javadoc-cleanup@v1.2.0
      with:
        path-to-root: docs
    
    - name: Log javadoc-cleanup output
      run: |
        echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"
    
    - name: Commit documentation changes
      run: |
        if [ $(git status | grep -c "**/*.html") == "0" ]; then
          git checkout .
        else
          git config --global user.name 'Docs Bot'
          git config --global user.email 'DOCS-BOT@users.noreply.github.com'
          git add -A
          git commit -m "Update documentation automatically"
          git push
        fi
