name: "tagged-release"

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11 
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    
    - run: mkdir staging && cp target/JSON-tools*.jar staging
    - name: Upload jar file
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE.txt
          staging/*.jar
